(()=>{const D=window.TRIP_DATA,S='japanTripStateV1';let state=JSON.parse(localStorage.getItem(S)||'{"done":{},"booking":{},"notes":{},"favorites":{}}');let view='today',manualDay=null;const app=document.querySelector('#app'),tabs=document.querySelector('#tabs');const save=()=>localStorage.setItem(S,JSON.stringify(state));const maps=q=>'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(q||'');const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));const fmt=d=>d?new Date(d+'T12:00:00').toLocaleDateString('he-IL',{day:'numeric',month:'numeric',year:'numeric'}):'';const dayById=id=>D.days.find(x=>x.id===id);const currentDay=()=>{if(manualDay)return dayById(manualDay);let iso=new Date().toLocaleDateString('sv-SE',{timeZone:D.settings['אזור זמן']||'Asia/Tokyo'});return D.days.find(d=>d.date===iso)||D.days[0]};
const tabList=[['today','היום'],['days','כל הימים'],['bookings','הזמנות'],['food','אוכל'],['hotels','מלונות'],['phrases','יפנית'],['settings','הגדרות']];tabs.innerHTML=tabList.map(t=>`<button data-view="${t[0]}">${t[1]}</button>`).join('');tabs.onclick=e=>{let b=e.target.closest('button');if(b){view=b.dataset.view;render()}};
function eventHTML(e){let done=!!state.done[e.id];return `<div class="event"><div class="eventtime">${esc(e.start)}${e.end?'–'+esc(e.end):''}</div><h3>${esc(e.title)}</h3><p>${esc(e.description)}</p>${e.transport?`<span class="badge">${esc(e.transport)}</span>`:''}<div class="actions">${e.mapsQuery?`<a class="btn secondary" target="_blank" href="${maps(e.mapsQuery)}">ניווט</a>`:''}<label class="check"><input type="checkbox" data-done="${e.id}" ${done?'checked':''}> בוצע</label></div></div>`}
function dayCard(d,full=true){let ev=D.schedule.filter(x=>x.dayId===d.id).sort((a,b)=>a.order-b.order);return `<section class="hero"><div class="meta">יום ${d.day} • ${fmt(d.date)} • ${esc(d.weekday)}</div><h2>${esc(d.title)}</h2><p>${esc(d.subtitle)}</p><span class="badge">עומס: ${esc(d.load)}</span>${d.holiday?'<span class="badge holiday">חג</span>':''}</section>${full?`<section class="card"><h2>לוח הזמנים</h2><div class="timeline">${ev.map(eventHTML).join('')}</div></section><section class="card"><h2>חשוב לדעת</h2><ul class="clean">${d.important.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><h2>מה לקחת</h2><ul class="clean">${d.take.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section><section class="card"><h2>מסעדות מתאימות</h2>${D.restaurants.filter(r=>r.days.includes(d.id)||r.days.includes(String(d.day))||r.days.includes('day-'+String(d.day).padStart(2,'0'))).map(foodCard).join('')||'<p>אין מסעדות משויכות ליום זה.</p>'}</section>`:''}`}
function foodCard(r){return `<article class="card"><h3>${esc(r.name)}</h3><div class="meta">${esc(r.area)} • ${esc(r.cuisine)} • ${esc(r.price)}</div><p><strong>ללא חזיר:</strong> ${esc(r.porkStatus)}</p><p>${esc(r.recommended)}</p><p>${esc(r.notes)}</p><div class="actions"><a class="btn secondary" target="_blank" href="${maps(r.mapsQuery||r.name)}">Google Maps</a>${r.website?`<a class="btn secondary" target="_blank" href="${esc(r.website)}">אתר</a>`:''}<button class="btn ${state.favorites[r.id]?'green':'secondary'}" data-fav="${r.id}">★</button></div></article>`}
function renderTodayView(dayData) {
  const container = document.getElementById('app-content');
  
  let html = `
    <div class="today-hero">
      <img src="${dayData.heroImage || 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?q=80&w=800'}" alt="${dayData.title}">
      <div class="today-hero-overlay">
        <span class="today-badge">${dayData.dateTag || 'היום'}</span>
        <h2>${dayData.title}</h2>
      </div>
    </div>
    <div class="activities-list">
  `;

  dayData.activities.forEach(act => {
    html += `
      <div class="activity-card">
        <div class="card-header">
          <h3 class="activity-title">${act.title}</h3>
          ${act.time ? `<span class="activity-time">${act.time}</span>` : ''}
        </div>
        <p class="activity-desc">${act.description || ''}</p>
        ${act.mapUrl ? `
          <a href="${act.mapUrl}" target="_blank" class="btn-map">
            📍 פתח במפות Google
          </a>
        ` : ''}
      </div>
    `;
  });

  html += `</div>`;
  container.innerHTML = html;
}
function renderDays(){app.innerHTML=`<input class="search" id="search" placeholder="חיפוש יום, מקום או פעילות"><div id="dayList">${D.days.map(d=>`<article class="card"><div class="meta">יום ${d.day} • ${fmt(d.date)}</div><h2>${esc(d.title)}</h2><p>${esc(d.city)} • עומס ${esc(d.load)}</p><button class="btn" data-open-day="${d.id}">פתיחת היום</button></article>`).join('')}</div>`;document.querySelector('#search').oninput=e=>{let q=e.target.value.toLowerCase();document.querySelectorAll('#dayList article').forEach(x=>x.classList.toggle('hidden',!x.innerText.toLowerCase().includes(q)))}}
function renderBookings(){let rank={קריטית:0,גבוהה:1,בינונית:2,נמוכה:3};let b=[...D.bookings].sort((a,z)=>(rank[a.priority]??9)-(rank[z.priority]??9));app.innerHTML=`<div class="filters"><button data-bfilter="all">הכול</button><button data-bfilter="open">פתוח</button><button data-bfilter="booked">הוזמן</button></div><div id="bookingList">${b.map(x=>`<article class="card" data-status="${state.booking[x.id]||x.status}"><h3>${esc(x.name)}</h3><div class="meta">${fmt(x.useDate)} • ${esc(x.time)} • ${esc(x.priority)}</div><p><strong>יעד:</strong> ${fmt(x.deadline)} | <strong>עלות:</strong> ${esc(x.cost)}</p><p>${esc(x.notes)}</p><div class="actions">${x.url?`<a class="btn secondary" target="_blank" href="${esc(x.url)}">הזמנה</a>`:''}<button class="btn" data-book="${x.id}">${(state.booking[x.id]||x.status)==='הוזמן'?'ביטול סימון':'סימון כהוזמן'}</button></div></article>`).join('')}</div>`}
function renderFood(){app.innerHTML=`<input class="search" id="search" placeholder="חיפוש מסעדה, אזור או מטבח">${D.restaurants.map(foodCard).join('')}`;document.querySelector('#search').oninput=e=>{let q=e.target.value.toLowerCase();document.querySelectorAll('main article').forEach(x=>x.classList.toggle('hidden',!x.innerText.toLowerCase().includes(q)))}}
function renderHotels(){app.innerHTML=D.hotels.map(h=>`<article class="card"><h2>${esc(h.name)}</h2><p>${esc(h.city)}<br>${esc(h.address)}<br>${esc(h.phone)}</p><p>${esc(h.notes)}</p><div class="actions"><a class="btn" target="_blank" href="${maps(h.mapsQuery||h.name)}">ניווט למלון</a></div></article>`).join('')}
function japaneseVoice(){const voices=window.speechSynthesis?.getVoices?.()||[];return voices.find(v=>v.lang==='ja-JP')||voices.find(v=>String(v.lang).toLowerCase().startsWith('ja'))||null}
function speakJapanese(text,slow=false){if(!('speechSynthesis' in window)||!('SpeechSynthesisUtterance' in window)){alert('המכשיר אינו תומך בהשמעת טקסט.');return}window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='ja-JP';u.rate=slow?.72:.9;u.pitch=1;u.volume=1;const v=japaneseVoice();if(v)u.voice=v;u.onerror=()=>alert('לא ניתן להשמיע כרגע. ודאו שמותקן קול יפני במכשיר.');window.speechSynthesis.speak(u)}
function stopJapanese(){if('speechSynthesis' in window)window.speechSynthesis.cancel()}
function renderPhrases(){const supported=('speechSynthesis' in window)&&('SpeechSynthesisUtterance' in window);app.innerHTML=`${supported?'':'<div class="notice">המכשיר אינו תומך בהשמעת טקסט. עדיין ניתן להעתיק את המשפט.</div>'}`+D.phrases.map(p=>{const encoded=encodeURIComponent(p.ja);return `<article class="card phrase-card"><div class="meta">${esc(p.category)}</div><h3>${esc(p.he)}</h3><button class="japanese-text" data-speak="${encoded}" aria-label="השמעת המשפט ביפנית">${esc(p.ja)}</button><p>${esc(p.roman)}</p><div class="actions"><button class="btn green" data-speak="${encoded}" ${supported?'':'disabled'}>🔊 השמעה</button><button class="btn secondary" data-slow="${encoded}" ${supported?'':'disabled'}>🐢 לאט</button><button class="btn secondary" data-stop="1" ${supported?'':'disabled'}>⏹ עצירה</button><button class="btn secondary" data-copy="${esc(p.ja)}">העתקה</button></div></article>`}).join('')}
function renderSettings(){app.innerHTML=`<article class="card install"><h2>התקנה</h2><p><strong>iPhone:</strong> Safari → שיתוף → הוספה למסך הבית → פתיחה כיישום.</p><p><strong>Android:</strong> Chrome → תפריט → Add to Home screen → Install.</p><button class="btn" id="installBtn">התקנה באנדרואיד</button></article><article class="card"><h2>גיבוי אישי</h2><p>הסימונים וההערות נשמרים רק במכשיר.</p><div class="actions"><button class="btn secondary" id="exportBtn">ייצוא גיבוי</button><label class="btn secondary">ייבוא<input id="importFile" type="file" accept="application/json" hidden></label><button class="btn secondary" id="resetBtn">איפוס</button></div></article><p class="footer-note">${esc(D.settings['שם הטיול']||'')} • גרסת נתונים ${esc(D.version)}</p>`;document.querySelector('#exportBtn').onclick=()=>{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='trip-backup.json';a.click()};document.querySelector('#importFile').onchange=e=>{let r=new FileReader();r.onload=()=>{state=JSON.parse(r.result);save();render()};r.readAsText(e.target.files[0])};document.querySelector('#resetBtn').onclick=()=>{if(confirm('למחוק את כל הסימונים המקומיים?')){localStorage.removeItem(S);location.reload()}};if(window._installPrompt)document.querySelector('#installBtn').onclick=()=>window._installPrompt.prompt();else document.querySelector('#installBtn').disabled=true}
function render(){document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));({today:renderToday,days:renderDays,bookings:renderBookings,food:renderFood,hotels:renderHotels,phrases:renderPhrases,settings:renderSettings}[view]||renderToday)()}
app.onclick=e=>{let d=e.target.dataset;if(d.done){state.done[d.done]=e.target.checked;save()}if(d.openDay){manualDay=d.openDay;view='today';render()}if(d.book){state.booking[d.book]=(state.booking[d.book]==='הוזמן'?'':'הוזמן');save();render()}if(d.fav){state.favorites[d.fav]=!state.favorites[d.fav];save();render()}if(d.speak){speakJapanese(decodeURIComponent(d.speak),false)}if(d.slow){speakJapanese(decodeURIComponent(d.slow),true)}if(d.stop){stopJapanese()}if(d.copy){navigator.clipboard.writeText(d.copy);e.target.textContent='הועתק'}};document.querySelector('#todayBtn').onclick=()=>{manualDay=null;view='today';render()};document.querySelector('#darkBtn').onclick=()=>document.body.classList.toggle('auto-dark');document.querySelector('#menuBtn').onclick=()=>{view='settings';render()};if('speechSynthesis' in window){window.speechSynthesis.getVoices();window.speechSynthesis.onvoiceschanged=()=>window.speechSynthesis.getVoices()};window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();window._installPrompt=e});if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('service-worker.js');document.querySelector('#appTitle').textContent=D.settings['שם הטיול']||'הטיול שלי';render()})();
